extraction:
  cpp:
    after_prepare: 
      - python report.py 70
  cobol:
    after_prepare: 
      - python report.py 70
  csharp:
    after_prepare: 
      - python report.py 70
  java:
    after_prepare: 
      - python report.py 70
  javascript:
    after_prepare: 
      - python report.py 70
  python:
    after_prepare: 
      - python report.py 70
